name: Clone-Crds
on:
  push:
    branches:
      - master
jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2
      - name: Diff Commits
        # Give an id to the step, so we can reference it later
        id: diff-commits
        run: |
          echo "1"
          # Diff HEAD with the previous commit
          diff=$(git diff --name-only HEAD^ HEAD)
          echo "$diff"
          # Check if k8s/crds.yaml has been changed
          changed=$(echo $diff | grep k8s/crds.yaml || true)
          echo "$changed"
          echo "changed=$changed" >> $GITHUB_OUTPUT
      # Run the step only with "changed" equals "True"
      - name: Create Pull Request
        if: steps.diff-commits.outputs.changed
        uses: yangchiu/bot/copy-files-and-create-pr-action@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        with:
          source_folder: k8s/crds.yaml
          destination_repo: 'yyz-field/copy'
          destination_folder: chart/templates/crds.yaml
          destination_base_branch: master
          destination_head_branch: github-actions-clone-crds-yaml
          user_email: github-actions@example.com
          user_name: github-actions
          pr_title: test123
          commit_msg: here
