name: Community-Issue
on:
  issues:
    types: [opened]
jobs:
  community:
    runs-on: ubuntu-latest
    steps:
      - name: Is Longhorn Member
        uses: tspascoal/get-user-teams-membership@v1.0.4
        id: is-longhorn-member
        with:
          username: ${{ github.event.issue.user.login }}
          organization: yyz-field
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
      - name: Add To Community Project
        uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: project1
          COLUMN: New
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
