name: Generate-SBOM
on:
  push:
    branches:
      - 'master'
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.5.0
    - name: Generate Key
      run: |
        cosign generate-key-pair
      env:
        COSIGN_PASSWORD: ""
    - name: Generate SBOM
      run: |
        mkdir sbom
        cp cosign.pub sbom/cosign.pub
        syft longhornio/longhorn-manager:v1.6.0 -o json --platform=linux/amd64 > sbom/longhorn-manager-v1.6.0-amd64.sbom
    - name: Sign SBOM
      run: |
        echo $COSIGN_PRIVATE_KEY > sbom/cosign.key
        cosign sign-blob -y sbom/longhorn-manager-v1.6.0-amd64.sbom --key cosign.key --output sbom/longhorn-manager-v1.6.0-amd64.sig
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: sbom
    - name: Verify SBOM
      run: |
        cosign verify-blob --key sbom/cosign.pub --signature $(cat sbom/longhorn-manager-v1.6.0-amd64.sig) sbom/longhorn-manager-v1.6.0-amd64.sbom
#    - name: Tar Assets
#      run: |
#        cp cosign.pub sbom/cosign.pub
#        tar zcvf sbom.tar.gz sbom
